// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEmployee(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetEmployeeByUserID(ctx context.Context, userID pgtype.UUID) (Employee, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
